# Generated by Django 4.1.5 on 2023-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="hour",
            field=models.TimeField(),
        ),
    ]
