# Generated by Django 4.1.5 on 2023-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_date_alter_transaction_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="typetransaction",
            field=models.CharField(
                choices=[
                    ("None", "Default"),
                    ("1", "Debito"),
                    ("2", "Boleto"),
                    ("3", "Financiamento"),
                    ("4", "Credito"),
                    ("5", "Emprestimo"),
                    ("6", "Vendas"),
                    ("7", "Ted"),
                    ("8", "Doc"),
                    ("9", "Aluguel"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
